### PR TITLE
Adding index to email on User model

### PR DESCRIPTION
**Pull request by jessecollier**

### CODE REVIEW

**Comment by glynn-zenefits** [comment]
Wait if we're going to do this can we increase the username length and email length? Both should be 254 though if the username was at least the same as email currently is (75) that would be okay too... 

More generally not sure we should be further forking django but if it's definite that we're never going to return to the fold then lets increase the username length, it causes tons of problems right now (it's why we have to use the email field instead so often).

**Comment by jessecollier** [comment]
:+1: We are going to maintain our own 1.7 fork. I think though we should keep it minimal, but I'm okay with db changes since its more difficult (and dangerous) to use auth swappable.

**Comment by zenryan** [comment]
This is going to cause migration conflicts in the future. I'm fairly certain a few user model migrations were added in 1.8 - we'll need to plan ahead for that if we ever decide to switch over.

**Comment by jessecollier** [comment]
i know, this is why i opted not to merge it.

**Pull request closed without merging**
