### PR TITLE
Make remove field, remove model migration operations NOOPs and raise …

### PR DESCRIPTION
**Pull request by zenryan**
…exception for rename models

### CODE REVIEW

**Comment by ZSujay** [comment]
It should not stop me from removing a field, if I did it the right way right?

And I believe this is the right order. Correct me if I'm wrong.

1) Removing all field usages 
    Adding to the excludes list in Tastypie resources
3) Remove the field and run the migration.
4) Remove the tastypie excludes (for sanity)

**Comment by zenryan** [comment]
You would be able to remove a field normally, this just prevents it from performing the db operation since that tends to bring down production while the migration is occurring. The idea here is that we'll save any data and also be able to remove it at some later point by running raw sql directly.

This is a WIP, remove field needs to be changed as well because there's a special case with fields that do not have default values. Additionally, @usmanghani comment regarding the rename is accurate, we should consider that case as well.

**Comment by glynn-zenefits** [comment]
@usmanghani the meta-issue is rename will always result in site outage as old code will be select/writing to the old column that no longer exists. If you do the rename alter the deploy then new code will blow up until the alter is run. Basically no matter what rename isn't possible without errors.

Basically a rename is large refactor and needs to be treated that way properly not just assumed to occur atomically.

**Comment by jessecollier** [comment]
the 1.7.7.1-optimized tag needs to be moved or a new one created

**Comment by jessecollier** [comment]
@zenryan  what happens if the field removed does not have a defualt?

**Comment by zenryan** [comment]
@jessecollier inserts will break if the column cannot be null

**Comment by glynn-zenefits** [comment]
> what happens if the field removed does not have a defualt?

The assumption is tests will fail (as Ryan says inserts for that model won't work at all). The advised procedure is to do a null=True migration and then the remove field migration.

If the above isn't enough or we have time I'd like to make a RemoveField on a non-nullable / non-default throw an exception.

**Pull request merged**
